apiVersion: v2
name: sd-regulatory-reporting
description: "BIAN Service Domain: Regulatory Reporting (Process pattern, Risk and Compliance)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Risk and Compliance"
  bian/business-domain: "Compliance"
  bian/asset-type: "Regulatory Report"
  bian/control-record: "Regulatory Report Procedure"
